# -*- coding: utf-8 -*-
"""sem7 lr4 Brazhkina AD.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/184zsrPzckaDtPJfAXDbZhMH1ToYstc06

# Лабораторная работа 4

Бражкина А.Д.

```
[ {"institute_name":"", "url": "", "dep_list": 
  [
   {"dep_name": "кафедра", "head_name":"имя", "email":"почта"},
   ...
  ]}, 
 ...
]
```
"""

from urllib.request import urlopen
from bs4 import BeautifulSoup
html = urlopen('https://www.herzen.spb.ru/main/structure/inst/')
bs = BeautifulSoup(html, "html.parser")
nameList = bs.find('td',{'class':'blockwh'})
print(nameList)

result = []
inst_list = nameList.div.ul.contents
print(inst_list)
for inst in inst_list:
    result.append({'institute_name':inst.a.get_text(), 'url':'https://www.herzen.spb.ru'+inst.a['href']})
print(result)

html = urlopen('https://atlas.herzen.spb.ru/faculty.php')
bs2 = BeautifulSoup(html, "html.parser")
nameList2 = bs2.findAll('a',{'class':'alist'})
print(nameList2)

import re
import pandas as pd
from tabulate import tabulate

dep_list = []
inst = {}

for _ in nameList2:
  name = _.get_text() # получаем название института/факультета или кафедры

  if _.get('href') == "faculty.php": # пробегаемся только по факультетам и институтам, без кафедр
    name = name.split(' ') # e.g. факультет безопасности жизнедеятельности -> ['факультет', 'безопасности', 'жизнедеятельности']

    for el in result: 
      
      if re.search(re.compile(name[1]) , el['institute_name']): 
        inst.update({"dep_list": dep_list})
        dep_list = []
        inst = el
  
  
  else:
    
    if re.search("кафедра", name):
      url = "https://atlas.herzen.spb.ru/" + _.get('href')
      dep = BeautifulSoup(urlopen(url), "html.parser")

      headings = dep.find_all('h3', {'class':'mm'})

      for el in headings:
        if 'Заведующий' in el.get_text():
          head_name = el.next_sibling.get_text().split(',')[0]
      
      teachs = dep.find_all('a',{'href':re.compile("teacher")})
      
      for el in teachs:
        if head_name in el.get_text():
          head_url = "https://atlas.herzen.spb.ru/" + el.get('href')
          head_bs = BeautifulSoup(urlopen(head_url), "html.parser")
          email = head_bs.find('a',{'href':re.compile('@')})
      
      
      dep_list.append({"dep_name":name, "url":url, "head_name":head_name, "email":email.get('href')})

df = pd.DataFrame(result)
print(tabulate(df, headers='keys', tablefmt='psql'))